import assert from 'node:assert/strict';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { test } from 'node:test';
import { createAgentSession, DefaultResourceLoader, ModelRuntime, SessionManager, SettingsManager } from '@earendil-works/pi-coding-agent';
import { Type } from '@earendil-works/pi-ai';
import { fauxProvider, fauxAssistantMessage, fauxToolCall } from '@earendil-works/pi-ai/providers/faux';
import extension from '../index.ts';

test('host Chain holds dependent across pause and reload, then hands off only the continued final answer', {timeout:10000}, async()=>{
 const directory=await mkdtemp(join(tmpdir(),'pi-groups-'));const old={agents:process.env.PI_SUBAGENT_AGENTS,storage:process.env.PI_SUBAGENT_STORAGE};process.env.PI_SUBAGENT_AGENTS=directory;process.env.PI_SUBAGENT_STORAGE=join(directory,'runs');
 const timer=globalThis.setTimeout;globalThis.setTimeout=((fn: (...args: unknown[]) => void,delay?: number,...args: unknown[])=>timer(fn,delay===60000?40:delay===48000?30:delay,...args)) as typeof setTimeout;
 let session:Awaited<ReturnType<typeof createAgentSession>>['session']|undefined;let child='';let group='';let work=0;let phase='start';const seen:string[]=[];
 try{
  await writeFile(join(directory,'scout.md'),'---\nname: scout\ndescription: Original frozen role\ntools: hold\n---\nOriginal role.');const faux=fauxProvider();
  faux.setResponses(Array.from({length:50},()=>context=>{
   const parent=context.messages.some(m=>m.role==='system'&&m.toolsAdded?.some(t=>t.name==='subagent'));
   const last=context.messages.at(-1);
   if(parent){
    if(last?.role==='toolResult')return fauxAssistantMessage('Parent settled.');
    const args: Record<string, string | number | {task:string}[] | null> =phase==='start'?{agent:'scout',chain:[{task:'First'},{task:'Second'}],timeoutMinutes:1}:phase==='status'?{run:group}:{resume:child,reassessment:'Finish retained work',timeoutMinutes:null};
    return fauxAssistantMessage([fauxToolCall(phase==='status'?'subagent_status':'subagent',args,{id:phase})],{stopReason:'toolUse'});
   }
   const text=JSON.stringify(context.messages);seen.push(text);
   const latestUser=context.messages.findLast(m=>m.role==='user');const latest=JSON.stringify(latestUser);
   if(latest.includes('Produce a final tool-free handoff'))return fauxAssistantMessage('HANDOFF: unfinished');
   if(latest.includes('Parent reassessment: Finish retained work')){assert.match(text,/Original role/);assert.doesNotMatch(text,/Changed role/);return fauxAssistantMessage('FINAL: genuine answer');}
   if(text.includes('Second'))return fauxAssistantMessage('Dependent final answer');
   if(!context.messages.some(m=>m.role==='toolResult'))return fauxAssistantMessage([fauxToolCall('hold',{}, {id:'hold-first'})],{stopReason:'toolUse'});
   return fauxAssistantMessage('Attempt ended');
  }));
  const models=await ModelRuntime.create({authPath:join(directory,'auth.json'),modelsPath:null,modelsStorePath:join(directory,'models.json'),refreshOnCreate:false});models.registerNativeProvider(faux.provider);const manager=SessionManager.inMemory(directory);const settings=SettingsManager.inMemory({defaultTools:['subagent','subagent_status']});
  async function open(){const loader=new DefaultResourceLoader({cwd:directory,agentDir:directory,settingsManager:settings,noExtensions:true,noSkills:true,noThemes:true,noPromptTemplates:true,extensionFactories:[extension,pi=>pi.registerTool({name:'hold',label:'Hold',exposure:'codemode',description:'Controlled tool boundary',parameters:Type.Object({}),async execute(){work++;await new Promise(resolve=>timer(resolve,120));return {content:[],details:undefined};}})]});await loader.reload();assert.deepEqual(loader.getExtensions().errors,[]);({session}=await createAgentSession({cwd:directory,agentDir:directory,modelRuntime:models,model:faux.getModel(),sessionManager:manager,settingsManager:settings,resourceLoader:loader,thinkingLevel:'off'}));await session.bindExtensions({mode:'print'});}
  await open();await session!.prompt('Start chain.');const result=session!.messages.findLast(m=>m.role==='toolResult'&&m.toolName==='subagent');assert.ok(result?.role==='toolResult');const held=result.details as {id:string;steps:{id:string;status:string}[];presentation:{entries:{phase:string}[]}};
  assert.equal(held.steps.length,1,'Paused child must not start its dependent');assert.equal(held.steps[0].status,'paused');assert.deepEqual(held.presentation.entries.map(e=>e.phase),['run','pending']);assert.ok(held.id);child=held.steps[0].id;group=held.id;assert.equal(work,1);
  await session!.reload();phase='status';await session!.prompt('Inspect retained group.');const status=session!.messages.findLast(m=>m.role==='toolResult');assert.ok(status?.role==='toolResult');assert.deepEqual((status.details as typeof held).presentation.entries.map(e=>e.phase),['run','pending']);assert.equal(work,1);
  await writeFile(join(directory,'scout.md'),'---\nname: scout\ndescription: Changed role\ntools: hold\n---\nChanged role.');phase='continue';await session!.prompt('Continue held child.');const continued=session!.messages.findLast(m=>m.role==='toolResult'&&m.toolName==='subagent');assert.ok(continued?.role==='toolResult');const final=continued.details as typeof held;assert.deepEqual(final.steps.map(r=>r.status),['succeeded','succeeded']);assert.equal(work,1,'Continuation must not replay completed side effect');const dependent=seen.find(t=>t.includes('Answer from the previous step in this chain:'));assert.ok(dependent);assert.match(dependent,/FINAL: genuine answer/);assert.doesNotMatch(dependent,/HANDOFF: unfinished/);
 }finally{globalThis.setTimeout=timer;if(session){await session.extensionRunner.emit({type:'session_shutdown',reason:'quit'});session.dispose();}for(const[key,value]of Object.entries({PI_SUBAGENT_AGENTS:old.agents,PI_SUBAGENT_STORAGE:old.storage})){if(value===undefined)delete process.env[key];else process.env[key]=value;}await rm(directory,{recursive:true,force:true});}
});

test('nonblocking Ordered returns its group, holds pending children and cancelling an unstarted child leaves Not run', {timeout:10000}, async()=>{
 const directory=await mkdtemp(join(tmpdir(),'pi-groups-control-'));const old={agents:process.env.PI_SUBAGENT_AGENTS,storage:process.env.PI_SUBAGENT_STORAGE};process.env.PI_SUBAGENT_AGENTS=directory;process.env.PI_SUBAGENT_STORAGE=join(directory,'runs');
 const timer=globalThis.setTimeout;globalThis.setTimeout=((fn:(...args:unknown[])=>void,delay?:number,...args:unknown[])=>timer(fn,delay===60000?40:delay===48000?30:delay,...args)) as typeof setTimeout;
 let session:Awaited<ReturnType<typeof createAgentSession>>['session']|undefined;let operation='start';let group='';let pending='';let first='';let work=0;
 try{
  await writeFile(join(directory,'scout.md'),'---\nname: scout\ndescription: Controlled group\ntools: hold\n---\nWork.');const faux=fauxProvider();faux.setResponses(Array.from({length:50},()=>context=>{
   const parent=context.messages.some(m=>m.role==='system'&&m.toolsAdded?.some(t=>t.name==='subagent'));
   if(parent){if(context.messages.at(-1)?.role==='toolResult')return fauxAssistantMessage('Parent remains available.');
    if(operation==='start')return fauxAssistantMessage([fauxToolCall('subagent',{agent:'scout',tasks:[{task:'First'},{task:'Second'}],nonblocking:true,timeoutMinutes:1},{id:'ordered-start'})],{stopReason:'toolUse'});
    return fauxAssistantMessage([fauxToolCall(operation==='wait'?'subagent_wait':operation==='inspect-first'?'subagent_status':'subagent_cancel',{run:operation==='cancel-child'?pending:operation==='inspect-first'?first:group,...(operation==='wait'?{waitSeconds:1}:{})},{id:operation})],{stopReason:'toolUse'});
   }
   const latest=JSON.stringify(context.messages.findLast(m=>m.role==='user'));
   if(latest.includes('tool-free handoff'))return fauxAssistantMessage([], {stopReason:'error',errorMessage:'Handoff failed'});
   if(!context.messages.some(m=>m.role==='toolResult'))return fauxAssistantMessage([fauxToolCall('hold',{}, {id:'held-tool'})],{stopReason:'toolUse'});
   return fauxAssistantMessage('Boundary reached');
  }));const models=await ModelRuntime.create({authPath:join(directory,'auth.json'),modelsPath:null,modelsStorePath:join(directory,'models.json'),refreshOnCreate:false});models.registerNativeProvider(faux.provider);const settings=SettingsManager.inMemory({defaultTools:['subagent','subagent_wait','subagent_status','subagent_cancel']});const loader=new DefaultResourceLoader({cwd:directory,agentDir:directory,settingsManager:settings,noExtensions:true,noSkills:true,noPromptTemplates:true,noThemes:true,extensionFactories:[extension,pi=>pi.registerTool({name:'hold',label:'Hold',exposure:'codemode',description:'Controlled tool',parameters:Type.Object({}),async execute(){work++;await new Promise(resolve=>timer(resolve,120));return {content:[],details:undefined};}})]});await loader.reload();assert.deepEqual(loader.getExtensions().errors,[]);({session}=await createAgentSession({cwd:directory,agentDir:directory,modelRuntime:models,model:faux.getModel(),sessionManager:SessionManager.inMemory(directory),settingsManager:settings,resourceLoader:loader,thinkingLevel:'off'}));
  const latest=()=>{const result=session!.messages.findLast(m=>m.role==='toolResult');assert.ok(result?.role==='toolResult');assert.equal(result.isError,false,JSON.stringify(result.content));return result;};
  await session.prompt('Start detached ordered work.');const start=latest().details as {id:string;presentation:{entries:{runId:string;phase:string}[]}};assert.ok(start.id,'Distinct group handle required');group=start.id;first=start.presentation.entries[0].runId;pending=start.presentation.entries[1].runId;assert.notEqual(group,first);assert.equal(start.presentation.entries[1].phase,'pending');
  operation='wait';await session.prompt('Wait for pause.');const paused=latest().details as {status:string;steps:{status:string;handoffLimitation:string}[];presentation:{entries:{phase:string}[]}};assert.equal(paused.status,'paused');assert.equal(paused.steps[0].status,'paused');assert.match(paused.steps[0].handoffLimitation,/Handoff unavailable/);assert.deepEqual(paused.presentation.entries.map(e=>e.phase),['run','pending']);assert.equal(work,1);
  operation='cancel-child';await session.prompt('Cancel just pending second child.');const cancelled=latest().details as {id:string;status:string};assert.equal(cancelled.id,pending);assert.equal(cancelled.status,'not-run');operation='inspect-first';await session.prompt('Inspect first child.');assert.equal((latest().details as {status:string}).status,'paused','Pending-child cancellation must not cancel its paused predecessor');
  operation='cancel-group';await session.prompt('Cancel whole group.');const stopped=latest().details as typeof paused;assert.equal(stopped.status,'aborted');assert.equal(stopped.steps[0].status,'aborted');assert.equal(work,1);
 }finally{globalThis.setTimeout=timer;if(session){await session.extensionRunner.emit({type:'session_shutdown',reason:'quit'});session.dispose();}for(const[key,value]of Object.entries({PI_SUBAGENT_AGENTS:old.agents,PI_SUBAGENT_STORAGE:old.storage})){if(value===undefined)delete process.env[key];else process.env[key]=value;}await rm(directory,{recursive:true,force:true});}
});

test('Parallel children finish independently of sibling pause, model failure and targeted cancellation without rebilling retrieval', {timeout:10000}, async()=>{
 const directory=await mkdtemp(join(tmpdir(),'pi-groups-parallel-'));const old={agents:process.env.PI_SUBAGENT_AGENTS,storage:process.env.PI_SUBAGENT_STORAGE};process.env.PI_SUBAGENT_AGENTS=directory;process.env.PI_SUBAGENT_STORAGE=join(directory,'runs');
 const timer=globalThis.setTimeout;globalThis.setTimeout=((fn:(...args:unknown[])=>void,delay?:number,...args:unknown[])=>timer(fn,delay===60000?40:delay===48000?30:delay,...args)) as typeof setTimeout;
 let session:Awaited<ReturnType<typeof createAgentSession>>['session']|undefined;let operation='start';let group='';let cancelledChild='';const effects:string[]=[];
 try{
  execFileSync('git',['init','-q',directory]);await writeFile(join(directory,'baseline.txt'),'Disposable');execFileSync('git',['-C',directory,'add','baseline.txt']);execFileSync('git',['-C',directory,'-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','Baseline']);
  await writeFile(join(directory,'scout.md'),'---\nname: scout\ndescription: Parallel fixture\ntools: hold\n---\nWork.');const faux=fauxProvider();faux.setResponses(Array.from({length:60},()=>context=>{
   const parent=context.messages.some(m=>m.role==='system'&&m.toolsAdded?.some(t=>t.name==='subagent'));
   if(parent){if(context.messages.at(-1)?.role==='toolResult')return fauxAssistantMessage('Parent remains available.');
    if(operation==='start')return fauxAssistantMessage([fauxToolCall('subagent',{agent:'scout',tasks:[{task:'Pause',timeoutMinutes:1},{task:'Success',timeoutMinutes:null},{task:'Fail',timeoutMinutes:null},{task:'Cancel',timeoutMinutes:null}],worktree:true,nonblocking:true},{id:'parallel-start'})],{stopReason:'toolUse'});
    return fauxAssistantMessage([fauxToolCall(operation==='cancel'?'subagent_cancel':'subagent_wait',{run:operation==='cancel'?cancelledChild:group, ...(operation==='cancel'?{}:{waitSeconds:1})},{id:operation})],{stopReason:'toolUse'});
   }
   const latest=JSON.stringify(context.messages.findLast(m=>m.role==='user'));
   if(latest.includes('tool-free handoff'))return fauxAssistantMessage('Paused unfinished sibling');
   const original=JSON.stringify(context.messages.find(m=>m.role==='user'));
   if(original.includes('Fail'))return fauxAssistantMessage([], {stopReason:'error',errorMessage:'Independent sibling failure'});
   if(!context.messages.some(m=>m.role==='toolResult'))return fauxAssistantMessage([fauxToolCall('hold',{kind:original.includes('Pause')?'Pause':original.includes('Cancel')?'Cancel':'Success'},{id:'effect'})],{stopReason:'toolUse'});
   return fauxAssistantMessage('Successful sibling final answer');
  }));const models=await ModelRuntime.create({authPath:join(directory,'auth.json'),modelsPath:null,modelsStorePath:join(directory,'models.json'),refreshOnCreate:false});models.registerNativeProvider(faux.provider);const settings=SettingsManager.inMemory({defaultTools:['subagent','subagent_wait','subagent_cancel']});const loader=new DefaultResourceLoader({cwd:directory,agentDir:directory,settingsManager:settings,noExtensions:true,noSkills:true,noPromptTemplates:true,noThemes:true,extensionFactories:[extension,pi=>pi.registerTool({name:'hold',label:'Hold',exposure:'codemode',description:'Interruptible fixture',parameters:Type.Object({kind:Type.String()}),async execute(_id,args,signal){effects.push(args.kind);await new Promise<void>((resolve,reject)=>{const abort=()=>{clearTimeout(delay);reject(new Error('Cancelled fixture'));};const delay=timer(()=>{signal?.removeEventListener('abort',abort);resolve();},args.kind==='Cancel'?2000:args.kind==='Pause'?120:5);signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)abort();});return {content:[],details:undefined};}})]});await loader.reload();assert.deepEqual(loader.getExtensions().errors,[]);({session}=await createAgentSession({cwd:directory,agentDir:directory,modelRuntime:models,model:faux.getModel(),sessionManager:SessionManager.inMemory(directory),settingsManager:settings,resourceLoader:loader,thinkingLevel:'off'}));
  const latest=()=>{const result=session!.messages.findLast(m=>m.role==='toolResult');assert.ok(result?.role==='toolResult');return result;};
  await session.prompt('Start independent siblings.');const start=latest().details as {id:string;presentation:{entries:{runId:string}[]}};assert.ok(start.id);group=start.id;cancelledChild=start.presentation.entries[3].runId;await new Promise(resolve=>timer(resolve,60));operation='cancel';await session.prompt('Cancel fourth child only.');operation='wait';await session.prompt('Inspect all retained sibling results.');const result=latest();const final=result.details as {steps:{status:string;cwd:string;usage:{cost:{total:number}}}[];presentation:{entries:{phase:string}[]}};
  assert.deepEqual(final.steps.map(r=>r.status),['paused','succeeded','failed','aborted']);assert.equal(new Set(final.steps.map(r=>r.cwd)).size,4,'Each sibling reacquires its actual isolated checkout');assert.deepEqual(effects.sort(),['Cancel','Pause','Success']);assert.ok(result.usage,'First management retrieval reports accrued child usage');operation='again';await session.prompt('Retrieve again.');assert.equal(latest().usage,undefined,'Repeated group retrieval cannot bill historical child work again');assert.deepEqual((latest().details as typeof final).steps.map(r=>r.usage.cost.total),final.steps.map(r=>r.usage.cost.total),'Recorded group cost stays truthful');
 }finally{globalThis.setTimeout=timer;if(session){await session.extensionRunner.emit({type:'session_shutdown',reason:'quit'});session.dispose();}for(const[key,value]of Object.entries({PI_SUBAGENT_AGENTS:old.agents,PI_SUBAGENT_STORAGE:old.storage})){if(value===undefined)delete process.env[key];else process.env[key]=value;}await rm(directory,{recursive:true,force:true});await rm(`${directory}-worktrees`,{recursive:true,force:true});}
});

test('Parallel capacity rejects each excess actual child with no later hidden queue', {timeout:10000}, async()=>{
 const directory=await mkdtemp(join(tmpdir(),'pi-groups-capacity-'));const old={agents:process.env.PI_SUBAGENT_AGENTS,storage:process.env.PI_SUBAGENT_STORAGE,capacity:process.env.PI_SUBAGENT_MAX_ACTIVE};process.env.PI_SUBAGENT_AGENTS=directory;process.env.PI_SUBAGENT_STORAGE=join(directory,'runs');process.env.PI_SUBAGENT_MAX_ACTIVE='1';
 let session:Awaited<ReturnType<typeof createAgentSession>>['session']|undefined;let group='';let phase='start';let effects=0;
 try{
  execFileSync('git',['init','-q',directory]);await writeFile(join(directory,'baseline.txt'),'Disposable');execFileSync('git',['-C',directory,'add','baseline.txt']);execFileSync('git',['-C',directory,'-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','Baseline']);await writeFile(join(directory,'scout.md'),'---\nname: scout\ndescription: Capacity fixture\ntools: hold\n---\nWork.');
  const faux=fauxProvider();faux.setResponses(Array.from({length:30},()=>context=>{const parent=context.messages.some(m=>m.role==='system'&&m.toolsAdded?.some(t=>t.name==='subagent'));if(parent){if(context.messages.at(-1)?.role==='toolResult')return fauxAssistantMessage('Parent settled.');return fauxAssistantMessage([fauxToolCall(phase==='start'?'subagent':'subagent_wait',phase==='start'?{agent:'scout',tasks:[{task:'A'},{task:'B'}],worktree:true,nonblocking:true}:{run:group,waitSeconds:1},{id:phase})],{stopReason:'toolUse'});}return context.messages.some(m=>m.role==='toolResult')?fauxAssistantMessage('Final answer'):fauxAssistantMessage([fauxToolCall('hold',{}, {id:'work'})],{stopReason:'toolUse'});}));
  const models=await ModelRuntime.create({authPath:join(directory,'auth.json'),modelsPath:null,modelsStorePath:join(directory,'models.json'),refreshOnCreate:false});models.registerNativeProvider(faux.provider);const settings=SettingsManager.inMemory({defaultTools:['subagent','subagent_wait']});const loader=new DefaultResourceLoader({cwd:directory,agentDir:directory,settingsManager:settings,noExtensions:true,noSkills:true,noPromptTemplates:true,noThemes:true,extensionFactories:[extension,pi=>pi.registerTool({name:'hold',label:'Hold',exposure:'codemode',description:'External tool boundary',parameters:Type.Object({}),async execute(){effects++;await new Promise(resolve=>setTimeout(resolve,100));return {content:[],details:undefined};}})]});await loader.reload();assert.deepEqual(loader.getExtensions().errors,[]);({session}=await createAgentSession({cwd:directory,agentDir:directory,modelRuntime:models,model:faux.getModel(),sessionManager:SessionManager.inMemory(directory),settingsManager:settings,resourceLoader:loader,thinkingLevel:'off'}));
  await session.prompt('Start bounded group.');let result=session.messages.findLast(m=>m.role==='toolResult');assert.ok(result?.role==='toolResult');group=(result.details as {id:string}).id;phase='wait';await session.prompt('Wait for admitted child.');result=session.messages.findLast(m=>m.role==='toolResult');assert.ok(result?.role==='toolResult');const final=result.details as {steps:{status:string}[];errors:Record<string,string>;presentation:{entries:{phase:string}[]}};assert.equal(final.steps.length,1);assert.equal(final.steps[0].status,'succeeded');assert.deepEqual(final.presentation.entries.map(e=>e.phase).sort(),['not-run','run']);assert.match(Object.values(final.errors).join(' '),/capacity 1: busy; no work queued/);assert.equal(effects,1);phase='again';await session.prompt('Inspect again.');assert.equal(effects,1,'Busy sibling must remain unstarted after capacity releases');
 }finally{if(session){await session.extensionRunner.emit({type:'session_shutdown',reason:'quit'});session.dispose();}for(const[key,value]of Object.entries({PI_SUBAGENT_AGENTS:old.agents,PI_SUBAGENT_STORAGE:old.storage,PI_SUBAGENT_MAX_ACTIVE:old.capacity})){if(value===undefined)delete process.env[key];else process.env[key]=value;}await rm(directory,{recursive:true,force:true});await rm(`${directory}-worktrees`,{recursive:true,force:true});}
});
